language: cpp
compiler: clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - clang-3.4
      - libclang-3.4-dev
      - llvm-3.4-dev
sudo: false
install:
  - export LLVM_VERSION=3.4
  - git clone --depth 1 'https://github.com/mruby/mruby.git'
  - export CXX="clang++ -std=c++11"
  - cmake -DCMAKE_BUILD_TYPE=DEBUG -DLLVM_CONFIG="llvm-config-$LLVM_VERSION" -DMRUBY_ROOT="$(pwd)/mruby" -DTEST_CLANG="clang" .
script:
  - make
  - make test
after_script:
  - cat Testing/Temporary/*.log
deploy:
  provider: releases
  api_key:
    secure: YnGPpASeSyIFjZkwzW8FowvIuFhOHwKXC4MJZaaaE9rJiak6feQtbNbWprBJRvStwuSWInjHhiXZOMsPIcIdbEDv/68ktPyQIfUQh/JboUmFVpzbQQfdcHnz7mktxiykm66jMWIfYoiNnAWrH9t+k2nuE+KsDjWHmZMnG/IVKbU=
  file: libmruby-clang-checker.so
  on:
    tags: true
