language: cpp
compiler: clang
matrix:
  include:
    - env: LLVM_VERSION=3.8
      addons:
        apt:
          sources:
          - llvm-toolchain-trusty
          packages:
          - libclang-3.8-dev
    - env: LLVM_VERSION=4.0
      addons:
        apt:
          sources:
          - llvm-toolchain-trusty-4.0
          packages:
          - libclang-4.0-dev
    - env: LLVM_VERSION=5.0
      addons:
        apt:
          sources:
          - llvm-toolchain-trusty-5.0
          packages:
          - libclang-5.0-dev
sudo: false
install:
  - git clone --depth 1 'https://github.com/mruby/mruby.git'
  - export CXX="clang++ -std=c++11"
  - cmake -DCMAKE_BUILD_TYPE=DEBUG -DLLVM_CONFIG="llvm-config-$LLVM_VERSION" -DMRUBY_ROOT="$(pwd)/mruby" -DTEST_CLANG="clang-$LLVM_VERSION" .
script:
  - make all test
after_script:
  - cat Testing/Temporary/*.log
deploy:
  provider: releases
  api_key:
    secure: YnGPpASeSyIFjZkwzW8FowvIuFhOHwKXC4MJZaaaE9rJiak6feQtbNbWprBJRvStwuSWInjHhiXZOMsPIcIdbEDv/68ktPyQIfUQh/JboUmFVpzbQQfdcHnz7mktxiykm66jMWIfYoiNnAWrH9t+k2nuE+KsDjWHmZMnG/IVKbU=
  file: libmruby-clang-checker.so
  on:
    tags: true
