langugage: cpp
compiler: clang
env:
  - LLVM_VERSION=3.4
  - LLVM_VERSION=3.5
  - LLVM_VERSION=3.6
install:
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-${LLVM_VERSION} main' >> /etc/apt/sources.list"
  - sudo sh -c "echo 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main' >> /etc/apt/sources.list"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-key update
  - sudo apt-get -qq update
  - sudo apt-get -qq install libclang-${LLVM_VERSION}-dev clang-${LLVM_VERSION} llvm-${LLVM_VERSION}-dev
  - git clone --depth 1 'https://github.com/mruby/mruby.git'
  - export CXX="clang++-${LLVM_VERSION} -std=c++11"
  - cmake -DCMAKE_BUILD_TYPE=DEBUG -DLLVM_CONFIG="llvm-config-$LLVM_VERSION" -DMRUBY_ROOT="$(pwd)/mruby" -DTEST_CLANG="clang-$LLVM_VERSION" .
script:
  - make
  - make test
after_script:
  - cat Testing/Temporary/*.log
